// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiempoProcesos.API.Data;

#nullable disable

namespace TiempoProcesos.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TiempoProcesos.API.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsProductiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.AdminUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreMostrar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsuarios", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.CalificacionMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<decimal>("CalificacionTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DesgloseMaquinas")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("CalificacionesMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.CodigoDesperdicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CodigosDesperdicio", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EncuestaCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AprobacionArranque")
                        .HasColumnType("boolean");

                    b.Property<int?>("AuxiliarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CantidadEvaluada")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CantidadProducir")
                        .HasColumnType("numeric");

                    b.Property<bool>("CorrectoRegistroFormatos")
                        .HasColumnType("boolean");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("EstadoProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("OperarioId")
                        .HasColumnType("integer");

                    b.Property<string>("OrdenProduccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TieneFichaTecnica")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuxiliarId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("OperarioId");

                    b.ToTable("EncuestasCalidad", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EncuestaNovedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDefectuosa")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.Property<string>("TipoNovedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("EncuestaNovedades", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CamaraCanal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CamaraCapacidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CamaraCondicionesFisicas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("CamaraFuncionaCorrectamente")
                        .HasColumnType("boolean");

                    b.Property<string>("CamaraMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CamaraModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CamaraResolucion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CamaraSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CamaraTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CamaraTipoOtro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContrasenaEquipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorreoUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiscoDuro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EscanerMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EscanerModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EscanerSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaInspeccion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImpresoraMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImpresoraModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImpresoraSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpDireccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MantenimientoRequerido")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MemoriaRam")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("MonitorBotonesCompletos")
                        .HasColumnType("boolean");

                    b.Property<bool>("MonitorColoresCorrectos")
                        .HasColumnType("boolean");

                    b.Property<string>("MonitorCondicionesFisicas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MonitorEnciende")
                        .HasColumnType("boolean");

                    b.Property<string>("MonitorMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MonitorModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MonitorSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MouseBotonesCompletos")
                        .HasColumnType("boolean");

                    b.Property<string>("MouseCondicionesFisicas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MouseFuncionaCorrectamente")
                        .HasColumnType("boolean");

                    b.Property<string>("MouseMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MouseModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MouseSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OtroSoftware")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OtrosDispositivos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PcBotonesCompletos")
                        .HasColumnType("boolean");

                    b.Property<string>("PcCondicionesFisicas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PcEnciende")
                        .HasColumnType("boolean");

                    b.Property<string>("PcInventario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PcMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PcModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PcSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PcTieneCdDvd")
                        .HasColumnType("boolean");

                    b.Property<bool>("PcTieneDiscoFlexible")
                        .HasColumnType("boolean");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Procesador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ProximoMantenimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SistemaOperativo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TecladoBotonesCompletos")
                        .HasColumnType("boolean");

                    b.Property<string>("TecladoCondicionesFisicas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TecladoFuncionaCorrectamente")
                        .HasColumnType("boolean");

                    b.Property<string>("TecladoMarca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TecladoModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TecladoSeReemplazo")
                        .HasColumnType("boolean");

                    b.Property<string>("TecladoSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UltimoMantenimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsuarioAsignado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VersionOffice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EquipoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("EquipoFotos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("GH_Cotizaciones", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_GastoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivoFactura")
                        .HasColumnType("text");

                    b.Property<string>("ArchivoFacturaNombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CotizacionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("GH_GastosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("GH_PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NIT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("GH_Proveedores", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("GH_Rubros", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PresupuestoMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("GH_TiposServicio", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.HistorialMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ProximoProgramado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tecnico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrabajoRealizado")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("HistorialMantenimientos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.LicenciaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("LicenciasEquipos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activa");

                    b.Property<decimal>("Importancia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Meta100Porciento")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetaDesperdicio")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int>("MetaRendimiento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SemaforoMax")
                        .HasColumnType("integer");

                    b.Property<int>("SemaforoMin")
                        .HasColumnType("integer");

                    b.Property<int>("SemaforoNormal")
                        .HasColumnType("integer");

                    b.Property<int>("TirosReferencia")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorPorTiro")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Maquinas", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrdenesProduccion", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.ProduccionDiaria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cambios")
                        .HasColumnType("integer");

                    b.Property<decimal>("Desperdicio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("DesperdicioBonificable")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("DiaLaborado")
                        .HasColumnType("integer");

                    b.Property<bool>("EsHorarioLaboral")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<decimal>("HorasDescanso")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("HorasMantenimiento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("HorasOperativas")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("HorasOtrosAux")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Novedades")
                        .HasColumnType("text");

                    b.Property<decimal>("PromedioHoraProductiva")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ReferenciaOP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("RendimientoFinal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TiempoFaltaTrabajo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TiempoOtroMuerto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TiempoPuestaPunto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TiempoReparacion")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TirosBonificables")
                        .HasColumnType("integer");

                    b.Property<int>("TirosDiarios")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalHorasAuxiliares")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalHorasProductivas")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalTiemposMuertos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorAPagar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorAPagarBonificable")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorTiroSnapshot")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProduccionDiaria", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.ToTable("Produccion_Cotizaciones");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CantidadHoras")
                        .HasColumnType("numeric");

                    b.Property<string>("FacturaPdfUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("text");

                    b.Property<string>("NumeroOP")
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoHoraId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoRecargoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.HasIndex("TipoHoraId");

                    b.HasIndex("TipoRecargoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produccion_Gastos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RubroId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("Produccion_PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecioCotizado")
                        .HasColumnType("numeric");

                    b.Property<int?>("RubroId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Produccion_Proveedores", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produccion_Rubros", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_TipoHora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produccion_TiposHora", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_TipoRecargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produccion_TiposRecargo", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.RegistroDesperdicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<int?>("CodigoDesperdicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.Property<string>("OrdenProduccion")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDesperdicioId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosDesperdicio", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.RendimientoOperarioMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("RendimientoPromedio")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalMaquinas")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTiros")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RendimientoOperariosMensual", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("SST_Cotizaciones");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_GastoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivoFactura")
                        .HasColumnType("text");

                    b.Property<string>("ArchivoFacturaNombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("SST_GastosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoServicioId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("SST_PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("SST_Proveedores", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SST_Rubros", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("SST_TiposServicio", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.ToTable("Talleres_Cotizaciones");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CantidadHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacturaPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroOP")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoHoraId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoRecargoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.HasIndex("TipoHoraId");

                    b.HasIndex("TipoRecargoId");

                    b.ToTable("Talleres_Gastos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Talleres_Personal");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RubroId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("Talleres_PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("NitCedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PrecioCotizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Talleres_Proveedores", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Talleres_Rubros", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.TiempoProceso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer");

                    b.Property<int>("Desperdicio")
                        .HasColumnType("integer");

                    b.Property<long>("Duracion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("OrdenProduccionId")
                        .HasColumnType("integer");

                    b.Property<int>("Tiros")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("OrdenProduccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TiempoProcesos", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EncuestaCalidad", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Auxiliar")
                        .WithMany()
                        .HasForeignKey("AuxiliarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TiempoProcesos.API.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Operario")
                        .WithMany()
                        .HasForeignKey("OperarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auxiliar");

                    b.Navigation("Maquina");

                    b.Navigation("Operario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EncuestaNovedad", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.EncuestaCalidad", "Encuesta")
                        .WithMany("Novedades")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EquipoFoto", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Equipo", "Equipo")
                        .WithMany("Fotos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Cotizacion", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.GH_Proveedor", "Proveedor")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_GastoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.GH_Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TiempoProcesos.API.Models.GH_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.GH_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.GH_TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_PresupuestoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.GH_TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Proveedor", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.GH_TipoServicio", "TipoServicio")
                        .WithMany("Proveedores")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_TipoServicio", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.GH_Rubro", "Rubro")
                        .WithMany("TiposServicio")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.HistorialMantenimiento", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Equipo", "Equipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.LicenciaEquipo", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Equipo", "Equipo")
                        .WithMany("Licencias")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.ProduccionDiaria", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Cotizacion", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Produccion_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Produccion_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Gasto", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId");

                    b.HasOne("TiempoProcesos.API.Models.Produccion_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.HasOne("TiempoProcesos.API.Models.Produccion_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Produccion_TipoHora", "TipoHora")
                        .WithMany()
                        .HasForeignKey("TipoHoraId");

                    b.HasOne("TiempoProcesos.API.Models.Produccion_TipoRecargo", "TipoRecargo")
                        .WithMany()
                        .HasForeignKey("TipoRecargoId");

                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Maquina");

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");

                    b.Navigation("TipoHora");

                    b.Navigation("TipoRecargo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_PresupuestoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Produccion_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Produccion_Proveedor", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Produccion_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.RegistroDesperdicio", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.CodigoDesperdicio", "CodigoDesperdicio")
                        .WithMany()
                        .HasForeignKey("CodigoDesperdicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TiempoProcesos.API.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodigoDesperdicio");

                    b.Navigation("Maquina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.RendimientoOperarioMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Cotizacion", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.SST_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_GastoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.SST_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.SST_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.SST_TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_PresupuestoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.SST_TipoServicio", "TipoServicio")
                        .WithMany("PresupuestosMensuales")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Proveedor", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.SST_TipoServicio", "TipoServicio")
                        .WithMany("Proveedores")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_TipoServicio", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.SST_Rubro", "Rubro")
                        .WithMany("TiposServicio")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Cotizacion", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Talleres_Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Talleres_Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Gasto", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Talleres_Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId");

                    b.HasOne("TiempoProcesos.API.Models.Talleres_Proveedor", "Proveedor")
                        .WithMany("Gastos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TiempoProcesos.API.Models.Talleres_Rubro", "Rubro")
                        .WithMany("Gastos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Produccion_TipoHora", "TipoHora")
                        .WithMany()
                        .HasForeignKey("TipoHoraId");

                    b.HasOne("TiempoProcesos.API.Models.Produccion_TipoRecargo", "TipoRecargo")
                        .WithMany()
                        .HasForeignKey("TipoRecargoId");

                    b.Navigation("Personal");

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");

                    b.Navigation("TipoHora");

                    b.Navigation("TipoRecargo");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_PresupuestoMensual", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Talleres_Rubro", "Rubro")
                        .WithMany("Presupuestos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.TiempoProceso", b =>
                {
                    b.HasOne("TiempoProcesos.API.Models.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiempoProcesos.API.Models.OrdenProduccion", "OrdenProduccion")
                        .WithMany()
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TiempoProcesos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Maquina");

                    b.Navigation("OrdenProduccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.EncuestaCalidad", b =>
                {
                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Equipo", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Licencias");

                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Proveedor", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_Rubro", b =>
                {
                    b.Navigation("TiposServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.GH_TipoServicio", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_Rubro", b =>
                {
                    b.Navigation("TiposServicio");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.SST_TipoServicio", b =>
                {
                    b.Navigation("PresupuestosMensuales");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Proveedor", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("TiempoProcesos.API.Models.Talleres_Rubro", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
