-- Insertar Usuarios desde SQL Server
INSERT INTO "Usuarios" ("Id", "Nombre", "Estado") VALUES
(1, 'Blandon Moreno Jose Lizandro', true),
(2, 'Cruz Pinto Alberto', true),
(3, 'Enrique Muñoz Hector Hilde', true),
(4, 'Escobar Cardona John Fredy', true),
(5, 'Martinez Osorno Karen Lizeth', true),
(6, 'Millan Salazar Magaly', true),
(7, 'Moreno Mendez Angel Julio', true),
(8, 'Moreno Urrea Marlene', true),
(9, 'Motta Talaga Leidy Jhoanna', true),
(10, 'Obando Higuita Jose Luis', true),
(11, 'Ramirez Romero Andres Mauricio', true),
(12, 'Sarmiento Rincon Yhan Otoniel', true),
(13, 'Velez Arana Robert De Jesus', true),
(14, 'Perdomo Rincon Gustavo Adolfo', true),
(15, 'Moriano Chiguas Yurde Arley', true),
(16, 'Bedoya Maria Fernanda', true),
(17, 'Morales Grueso Claudia Patricia', true),
(18, 'Gomez Ruiz William Hernan', true),
(19, 'Rodriguez Castaño Maria Alejandra', true),
(20, 'Rojas Collazos Joan Mauricio', true),
(21, 'Riascos Castillo Andres Felipe', true),
(22, 'Roldan Barona Erik Esteban', true),
(23, 'Renteria Mejia Nestor Alfonso', true),
(24, 'Mina Sinisterra Jhon Jairo', true),
(25, 'Valencia Mirquez Nicol', true),
(26, 'Uran Quintero Yohao Alexander', true),
(27, 'Preciado Rivas Johan Alexander', true),
(28, 'Jose Fernando Ruiz', true),
(29, 'Johan Alexander Preciado', true),
(30, 'Cristian Felipe Echavarria', true);

SELECT setval('"Usuarios_Id_seq"', 30, true);
