TRUNCATE TABLE "AdminUsuarios" RESTART IDENTITY CASCADE;
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('1', 'admin', '$2a$11$luyKFLM0zZh8W3ziyGQNIOxmYj9w87QSh19JMFzykVyLSNDT2B.1C', 'admin', 'Administrador Master');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('2', 'produccion', '$2a$11$r.UXZBHG2oUbR53Oz10Ck.6crMlhrg5Dvf9/jEDPIDCc7WbS1B6CC', 'produccion', 'Gerente Producción');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('3', 'sst', '$2a$11$.bdDQVv90BjuCJd7WR8OgOpI.Y0k/BldGb7SJf3fbBKSFyRTTXgz6', 'sst', 'Seguridad y Salud');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('4', 'gh', '$2a$11$ARQo7I.LYS07zKPU.T7bWOYLhqyx0fneVkxX514l1PpZolwkYyQxK', 'gh', 'Gestión Humana');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('5', 'talleres', '$2a$11$6XHC0rwrqYkAH5y3oAffZ.LJPJBDKTADVc73sLBkFYyU8fUGVav9S', 'talleres', 'Talleres y Despacho');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('6', 'presupuesto', '$2a$11$Jh60z4SYF7lfLo.eGO5uKOB2T14XGnqNscANQpYckSFL7e9Qf80IW', 'presupuesto', 'Presupuesto General');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('7', 'calidad', '$2a$11$.55NYQHp3yeI..XGwjUUm.E4ED1MGw5zD1Sjgn5.lb/1j3QXwF2qy', 'calidad', 'Control Calidad');
INSERT INTO "AdminUsuarios" ("Id", "Username", "PasswordHash", "Role", "NombreMostrar") VALUES ('8', 'develop', '$2a$11$i4y6NQYr.4w3nv92N.pS7OQRdrjudVJqN/4J/ZYXPnkh7A2yw/UoS', 'develop', 'Desarrollador');
SELECT setval('"AdminUsuarios_Id_seq"', (SELECT COALESCE(MAX("Id"), 1) FROM "AdminUsuarios") + 1, false);
