START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415182553_AddTipoTrabajoToPlanAccion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415182553_AddTipoTrabajoToPlanAccion', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417201535_CompleteQualitySurveyV2') THEN
    CREATE TABLE "TalleresExternos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        CONSTRAINT "PK_TalleresExternos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417201535_CompleteQualitySurveyV2') THEN
    CREATE TABLE "EncuestasCalidadTalleres" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TallerId" integer NOT NULL,
        "HoraLlegada" text NOT NULL,
        "HoraSalida" text NOT NULL,
        "OrdenProduccion" text NOT NULL,
        "NumeroRemision" text NOT NULL,
        "CantidadProducir" numeric(18,2) NOT NULL,
        "CantidadEvaluada" numeric(18,2) NOT NULL,
        "EstadoProceso" text NOT NULL,
        "TieneMuestra" boolean NOT NULL,
        "TipoProducto" text,
        "ConoceFormaEmpaque" boolean NOT NULL,
        "TieneRemision" boolean NOT NULL,
        "TieneInsumosCompletos" boolean NOT NULL,
        "VariacionTono" boolean NOT NULL,
        "QuebradoArrugado" boolean NOT NULL,
        "EsquinaDefectuosa" boolean NOT NULL,
        "PresenciaPestanas" boolean NOT NULL,
        "DesgasteImpresion" boolean NOT NULL,
        "Manchas" boolean NOT NULL,
        "ReservaPega" boolean NOT NULL,
        "GrafadoRoto" boolean NOT NULL,
        "NovedadBPM" boolean NOT NULL,
        "UsaCofia" boolean NOT NULL,
        "InsumosPendientes" boolean NOT NULL,
        "TipoInsumosPendientes" text,
        "Observaciones" text,
        "UsuarioId" integer NOT NULL,
        "FechaCreacion" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_EncuestasCalidadTalleres" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EncuestasCalidadTalleres_TalleresExternos_TallerId" FOREIGN KEY ("TallerId") REFERENCES "TalleresExternos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_EncuestasCalidadTalleres_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417201535_CompleteQualitySurveyV2') THEN
    CREATE INDEX "IX_EncuestasCalidadTalleres_TallerId" ON "EncuestasCalidadTalleres" ("TallerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417201535_CompleteQualitySurveyV2') THEN
    CREATE INDEX "IX_EncuestasCalidadTalleres_UsuarioId" ON "EncuestasCalidadTalleres" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417201535_CompleteQualitySurveyV2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260417201535_CompleteQualitySurveyV2', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" DROP CONSTRAINT "FK_EncuestasCalidadTalleres_Usuarios_UsuarioId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Usuarios" ADD "Area" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Tickets" ADD "Consecutivo" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Produccion_Cotizaciones" ADD "Cantidad" numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Produccion_Cotizaciones" ADD "Medida" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Produccion_Cotizaciones" ADD "ProductoId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Produccion_Cotizaciones" ADD "ValorUnitario" numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoDesgasteImpresion" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoEsquinaDefectuosa" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoGrafadoRoto" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoInsumosPendientes" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoManchas" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoNovedadBPM" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoPresenciaPestanas" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoQuebradoArrugado" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoReservaPega" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoUsaCofia" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD "FotoVariacionTono" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "Cronogramas_Actividades" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Operacion" text NOT NULL,
        "Categoria" text NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Cronogramas_Actividades" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "HojasVidaMaquinas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(100) NOT NULL,
        "NumeroInventario" character varying(50),
        "Marca" character varying(100),
        "Serie" character varying(100),
        "Modelo" character varying(100),
        "Color" character varying(50),
        "FechaCompra" timestamp without time zone,
        "VidaUtil" character varying(100),
        "FotoUrl" character varying(500),
        "EppsYRiesgos" text,
        "Senalizacion" text,
        "RiesgosAsociados" text,
        "Activo" boolean NOT NULL,
        "FechaRegistro" timestamp without time zone NOT NULL,
        "CodigoFormato" text NOT NULL,
        "VersionFormato" text NOT NULL,
        "Proceso" character varying(100),
        "Ubicacion" character varying(100),
        "Voltaje" character varying(50),
        "Corriente" character varying(50),
        "Potencia" character varying(50),
        "Dimensiones" character varying(100),
        "Peso" character varying(50),
        "OtroTecnico" text,
        CONSTRAINT "PK_HojasVidaMaquinas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "Produccion_Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(200) NOT NULL,
        "RubroId" integer NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Produccion_Productos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Produccion_Productos_Produccion_Rubros_RubroId" FOREIGN KEY ("RubroId") REFERENCES "Produccion_Rubros" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "BitacorasMaquinas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HojaVidaId" integer NOT NULL,
        "Fecha" timestamp without time zone NOT NULL,
        "Turno" character varying(50) NOT NULL,
        "Descripcion" text NOT NULL,
        "EstadoMaquina" character varying(50) NOT NULL,
        "RegistradoPor" character varying(100) NOT NULL,
        "FechaRegistro" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_BitacorasMaquinas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BitacorasMaquinas_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "Cronogramas_Registros" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HojaVidaId" integer NOT NULL,
        "ActividadId" integer NOT NULL,
        "Anio" integer NOT NULL,
        "Mes" integer NOT NULL,
        "Estado" integer NOT NULL,
        "Nota" text,
        CONSTRAINT "PK_Cronogramas_Registros" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cronogramas_Registros_Cronogramas_Actividades_ActividadId" FOREIGN KEY ("ActividadId") REFERENCES "Cronogramas_Actividades" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cronogramas_Registros_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "HojaVidaFotos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HojaVidaId" integer NOT NULL,
        "Url" character varying(500) NOT NULL,
        "FechaRegistro" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_HojaVidaFotos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HojaVidaFotos_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "MantenimientosHojaVida" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HojaVidaId" integer NOT NULL,
        "TipoMantenimiento" character varying(100) NOT NULL,
        "Fecha" timestamp without time zone NOT NULL,
        "EjecutadoPor" character varying(100),
        "Observacion" text,
        "FechaRegistro" timestamp without time zone NOT NULL,
        "Consecutivo" integer NOT NULL,
        "TicketId" integer,
        "TipoPersonal" text NOT NULL,
        CONSTRAINT "PK_MantenimientosHojaVida" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MantenimientosHojaVida_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE TABLE "MantenimientoFotos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MantenimientoId" integer NOT NULL,
        "Url" character varying(500) NOT NULL,
        "FechaRegistro" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_MantenimientoFotos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MantenimientoFotos_MantenimientosHojaVida_MantenimientoId" FOREIGN KEY ("MantenimientoId") REFERENCES "MantenimientosHojaVida" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_Produccion_Cotizaciones_ProductoId" ON "Produccion_Cotizaciones" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_BitacorasMaquinas_HojaVidaId" ON "BitacorasMaquinas" ("HojaVidaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_Cronogramas_Registros_ActividadId" ON "Cronogramas_Registros" ("ActividadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_Cronogramas_Registros_HojaVidaId" ON "Cronogramas_Registros" ("HojaVidaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_HojaVidaFotos_HojaVidaId" ON "HojaVidaFotos" ("HojaVidaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_MantenimientoFotos_MantenimientoId" ON "MantenimientoFotos" ("MantenimientoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_MantenimientosHojaVida_HojaVidaId" ON "MantenimientosHojaVida" ("HojaVidaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    CREATE INDEX "IX_Produccion_Productos_RubroId" ON "Produccion_Productos" ("RubroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "EncuestasCalidadTalleres" ADD CONSTRAINT "FK_EncuestasCalidadTalleres_AdminUsuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "AdminUsuarios" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    ALTER TABLE "Produccion_Cotizaciones" ADD CONSTRAINT "FK_Produccion_Cotizaciones_Produccion_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Produccion_Productos" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424153125_AddProductosToProduccion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260424153125_AddProductosToProduccion', '9.0.0');
    END IF;
END $EF$;
COMMIT;

