-- Marcar AddTipoTrabajoToPlanAccion como aplicado (las columnas ya existen)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260415182553_AddTipoTrabajoToPlanAccion', '9.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260415182553_AddTipoTrabajoToPlanAccion'
);

-- ====== Cambios de AddProductosToProduccion ======

-- Columnas en Produccion_Cotizaciones
ALTER TABLE "Produccion_Cotizaciones" ADD COLUMN IF NOT EXISTS "Cantidad" numeric(18,2);
ALTER TABLE "Produccion_Cotizaciones" ADD COLUMN IF NOT EXISTS "Medida" character varying(50);
ALTER TABLE "Produccion_Cotizaciones" ADD COLUMN IF NOT EXISTS "ProductoId" integer;
ALTER TABLE "Produccion_Cotizaciones" ADD COLUMN IF NOT EXISTS "ValorUnitario" numeric(18,2);

-- Columnas en EncuestasCalidadTalleres
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoDesgasteImpresion" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoEsquinaDefectuosa" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoGrafadoRoto" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoInsumosPendientes" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoManchas" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoNovedadBPM" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoPresenciaPestanas" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoQuebradoArrugado" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoReservaPega" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoUsaCofia" text;
ALTER TABLE "EncuestasCalidadTalleres" ADD COLUMN IF NOT EXISTS "FotoVariacionTono" text;

-- Otras columnas
ALTER TABLE "Tickets" ADD COLUMN IF NOT EXISTS "Consecutivo" integer NOT NULL DEFAULT 0;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS "Area" text NOT NULL DEFAULT '';

-- Tabla Produccion_Productos
CREATE TABLE IF NOT EXISTS "Produccion_Productos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(200) NOT NULL,
    "RubroId" integer NOT NULL,
    "Activo" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Produccion_Productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produccion_Productos_Produccion_Rubros_RubroId" FOREIGN KEY ("RubroId") REFERENCES "Produccion_Rubros" ("Id") ON DELETE CASCADE
);

-- Tabla HojasVidaMaquinas
CREATE TABLE IF NOT EXISTS "HojasVidaMaquinas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "NumeroInventario" character varying(50),
    "Marca" character varying(100),
    "Serie" character varying(100),
    "Modelo" character varying(100),
    "Color" character varying(50),
    "FechaCompra" timestamp without time zone,
    "VidaUtil" character varying(100),
    "FotoUrl" character varying(500),
    "EppsYRiesgos" text,
    "Senalizacion" text,
    "RiesgosAsociados" text,
    "Activo" boolean NOT NULL,
    "FechaRegistro" timestamp without time zone NOT NULL,
    "CodigoFormato" text NOT NULL,
    "VersionFormato" text NOT NULL,
    "Proceso" character varying(100),
    "Ubicacion" character varying(100),
    "Voltaje" character varying(50),
    "Corriente" character varying(50),
    "Potencia" character varying(50),
    "Dimensiones" character varying(100),
    "Peso" character varying(50),
    "OtroTecnico" text,
    CONSTRAINT "PK_HojasVidaMaquinas" PRIMARY KEY ("Id")
);

-- Tabla Cronogramas_Actividades
CREATE TABLE IF NOT EXISTS "Cronogramas_Actividades" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Operacion" text NOT NULL,
    "Categoria" text NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Cronogramas_Actividades" PRIMARY KEY ("Id")
);

-- Tabla BitacorasMaquinas
CREATE TABLE IF NOT EXISTS "BitacorasMaquinas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HojaVidaId" integer NOT NULL,
    "Fecha" timestamp without time zone NOT NULL,
    "Turno" character varying(50) NOT NULL,
    "Descripcion" text NOT NULL,
    "EstadoMaquina" character varying(50) NOT NULL,
    "RegistradoPor" character varying(100) NOT NULL,
    "FechaRegistro" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BitacorasMaquinas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BitacorasMaquinas_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
);

-- Tabla Cronogramas_Registros
CREATE TABLE IF NOT EXISTS "Cronogramas_Registros" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HojaVidaId" integer NOT NULL,
    "ActividadId" integer NOT NULL,
    "Anio" integer NOT NULL,
    "Mes" integer NOT NULL,
    "Estado" integer NOT NULL,
    "Nota" text,
    CONSTRAINT "PK_Cronogramas_Registros" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cronogramas_Registros_Cronogramas_Actividades_ActividadId" FOREIGN KEY ("ActividadId") REFERENCES "Cronogramas_Actividades" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Cronogramas_Registros_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
);

-- Tabla HojaVidaFotos
CREATE TABLE IF NOT EXISTS "HojaVidaFotos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HojaVidaId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "FechaRegistro" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_HojaVidaFotos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HojaVidaFotos_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
);

-- Tabla MantenimientosHojaVida
CREATE TABLE IF NOT EXISTS "MantenimientosHojaVida" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HojaVidaId" integer NOT NULL,
    "TipoMantenimiento" character varying(100) NOT NULL,
    "Fecha" timestamp without time zone NOT NULL,
    "EjecutadoPor" character varying(100),
    "Observacion" text,
    "FechaRegistro" timestamp without time zone NOT NULL,
    "Consecutivo" integer NOT NULL DEFAULT 0,
    "TicketId" integer,
    "TipoPersonal" text NOT NULL DEFAULT '',
    CONSTRAINT "PK_MantenimientosHojaVida" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MantenimientosHojaVida_HojasVidaMaquinas_HojaVidaId" FOREIGN KEY ("HojaVidaId") REFERENCES "HojasVidaMaquinas" ("Id") ON DELETE CASCADE
);

-- Tabla MantenimientoFotos
CREATE TABLE IF NOT EXISTS "MantenimientoFotos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MantenimientoId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "FechaRegistro" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_MantenimientoFotos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MantenimientoFotos_MantenimientosHojaVida_MantenimientoId" FOREIGN KEY ("MantenimientoId") REFERENCES "MantenimientosHojaVida" ("Id") ON DELETE CASCADE
);

-- Indices
CREATE INDEX IF NOT EXISTS "IX_Produccion_Cotizaciones_ProductoId" ON "Produccion_Cotizaciones" ("ProductoId");
CREATE INDEX IF NOT EXISTS "IX_Produccion_Productos_RubroId" ON "Produccion_Productos" ("RubroId");
CREATE INDEX IF NOT EXISTS "IX_BitacorasMaquinas_HojaVidaId" ON "BitacorasMaquinas" ("HojaVidaId");
CREATE INDEX IF NOT EXISTS "IX_Cronogramas_Registros_ActividadId" ON "Cronogramas_Registros" ("ActividadId");
CREATE INDEX IF NOT EXISTS "IX_Cronogramas_Registros_HojaVidaId" ON "Cronogramas_Registros" ("HojaVidaId");
CREATE INDEX IF NOT EXISTS "IX_HojaVidaFotos_HojaVidaId" ON "HojaVidaFotos" ("HojaVidaId");
CREATE INDEX IF NOT EXISTS "IX_MantenimientoFotos_MantenimientoId" ON "MantenimientoFotos" ("MantenimientoId");
CREATE INDEX IF NOT EXISTS "IX_MantenimientosHojaVida_HojaVidaId" ON "MantenimientosHojaVida" ("HojaVidaId");

-- FK entre EncuestasCalidadTalleres y AdminUsuarios (si no existe)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_EncuestasCalidadTalleres_AdminUsuarios_UsuarioId'
    ) THEN
        ALTER TABLE "EncuestasCalidadTalleres"
        ADD CONSTRAINT "FK_EncuestasCalidadTalleres_AdminUsuarios_UsuarioId"
        FOREIGN KEY ("UsuarioId") REFERENCES "AdminUsuarios" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

-- FK entre Produccion_Cotizaciones y Produccion_Productos (si no existe)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_Produccion_Cotizaciones_Produccion_Productos_ProductoId'
    ) THEN
        ALTER TABLE "Produccion_Cotizaciones"
        ADD CONSTRAINT "FK_Produccion_Cotizaciones_Produccion_Productos_ProductoId"
        FOREIGN KEY ("ProductoId") REFERENCES "Produccion_Productos" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

-- Marcar AddProductosToProduccion como aplicado
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260424153125_AddProductosToProduccion', '9.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260424153125_AddProductosToProduccion'
);
