INSERT INTO Usuarios (Nombre, Estado) VALUES ('Blandon Moreno Jose Lizandro', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Cruz Pinto Alberto', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Enrique Muñoz Hector Hilde', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Escobar Cardona John Fredy', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Martinez Osorno Karen Lizeth', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Millan Salazar Magaly', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Moreno Mendez Angel Julio', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Moreno Urrea Marlene', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Motta Talaga Leidy Jhoanna', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Obando Higuita Jose Luis', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Ramirez Romero Andres Mauricio', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Sarmiento Rincon Yhan Otoniel', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Velez Arana Robert De Jesus', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Perdomo Rincon Gustavo Adolfo', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Moriano Chiguas Yurde Arley', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Bedoya Maria Fernanda', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Morales Grueso Claudia Patricia', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Gomez Ruiz William Hernan', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Rodriguez Castaño Maria Alejandra', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Rojas Collazos Joan Mauricio', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Riascos Castillo Andres Felipe', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Roldan Barona Erik Esteban', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Renteria Mejia Nestor Alfonso', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Mina Sinisterra Jhon Jairo', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Valencia Mirquez Nicol', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Uran Quintero Yohao Alexander', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Preciado Rivas Johan Alexander', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Jose Fernando Ruiz', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Johan Alexander Preciado', 1);
INSERT INTO Usuarios (Nombre, Estado) VALUES ('Cristian Felipe Echavarria', 1);

(30 rows affected)
