CREATE TABLE IF NOT EXISTS "Talleres_Cotizaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProveedorId" integer NOT NULL,
    "RubroId" integer NOT NULL,
    "Anio" integer NOT NULL,
    "Mes" integer NOT NULL,
    "PrecioCotizado" numeric(18,2) NOT NULL,
    "FechaCotizacion" timestamp without time zone NOT NULL,
    "Descripcion" character varying(500),
    "Activo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Talleres_Cotizaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Talleres_Cotizaciones_Talleres_Proveedores_ProveedorId" FOREIGN KEY ("ProveedorId") REFERENCES "Talleres_Proveedores" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Talleres_Cotizaciones_Talleres_Rubros_RubroId" FOREIGN KEY ("RubroId") REFERENCES "Talleres_Rubros" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Talleres_Cotizaciones_ProveedorId" ON "Talleres_Cotizaciones" ("ProveedorId");
CREATE INDEX IF NOT EXISTS "IX_Talleres_Cotizaciones_RubroId" ON "Talleres_Cotizaciones" ("RubroId");
